title: "[삭제] "
labels: ["문서 삭제"]
body:
  - type: input
    attributes:
      label: Suggestions
      description: A description about suggestions to help you
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        This is text that will show up in the template!
